---
- name: Cambio de period para metricbeat
  hosts: all
  remote_user: ymedinas
  become: yes
  tasks:
    - name: Detener el servicio de metricbeat
      systemd:
       name: metricbeat
       state: stopped
      register: find_output

    - debug:
        var: find_output.status.Result

    - name: Copiar el nuevo archivo de configuracion
      copy:
        src: /root/ansible_dev_rn/elastic_cnf_file/system.yml_period_3m
        dest: /etc/metricbeat/modules.d/system.yml
        backup: yes

    - name: Iniciar Metricbeat
      systemd:
       state: started
       name: metricbeat

