---
- name: Cambio de period para metricbeat
  hosts: CentOS
#  remote_user: alberto
  tasks:
    - name: Copiar fichero hosts
      copy:
        src: /root/ansible_dev_rn/elastic_cnf_file/system.yml_period_3m
        dest: /etc/metricbeat/modules.d/system.yml
        backup: yes
#       become: true
#       become: root

    - name: Copiar Metricbeat
      copy:
        src: /root/metricbeat-7.8.0-x86_64.rpm
        dest: /tmp/metric_install.rpm
        backup: yes

    - name: Instalar el Metricbeat
      command: rpm -i /tmp/metric_install.rpm
      register: mymotd

    - name: Activar el modulo de systema
      command: metricbeat modules enable system

    - name: Reiniciar Metricbeat
      systemd:
       state: restarted
       daemon_reload: yes
       name: metricbeat

